aCC = gcc
CFLAGS = -Wall -Werror -ansi -lm

main.out : O_MAIN.o O_ADDCRIM.o O_BACKEND.o O_COMPRESSION.o O_EDITCRIM.o O_ENCRYPTION.o O_IMAGES.o O_SAVELOAD.o O_SEARCHDISPLAY.o
	$(CC) $(CFLAGS) -o main.out C_MAIN.c C_ADDCRIM.c C_BACKEND.c C_COMPRESSION.c C_EDITCRIM.c C_ENCRYPTION.c C_IMAGES.c C_SAVELOAD.c C_SEARCHDISPLAY.c

O_MAIN.o : C_MAIN.c H_ADDCRIM.h H_BACKEND.h H_COMPRESSION.h H_EDITCRIM.h H_ENCRYPTION.h H_IMAGES.h H_MAIN.h H_SAVELOAD.h H_SEARCHDISPLAY.h
	$(CC) $(CFLAGS) -c -o O_MAIN.o C_MAIN.c

O_ADDCRIM.o : C_ADDCRIM.c H_MAIN.h H_ADDCRIM.h H_BACKEND.h H_IMAGES.h 
	$(CC) $(CFLAGS) -c -o O_ADDCRIM.o C_ADDCRIM.c

O_BACKEND.o : C_BACKEND.c H_MAIN.h H_BACKEND.h
	$(CC) $(CFLAGS) -c -o O_BACKEND.o C_BACKEND.c

O_COMPRESSION.o : C_COMPRESSION.c H_COMPRESSION.h
	$(CC) $(CFLAGS) -c -o O_COMPRESSION.o C_COMPRESSION.c

O_EDITCRIM.o : C_EDITCRIM.c H_MAIN.h H_EDITCRIM.h
	$(CC) $(CFLAGS) -c -o O_EDITCRIM.o C_EDITCRIM.c

O_IMAGES.o : C_IMAGES.c H_MAIN.h H_IMAGES.h H_ENCRYPTION.h
	$(CC) $(CFLAGS) -c -o O_IMAGES.o C_IMAGES.c

O_ENCRYPTION.o : C_ENCRYPTION.c H_MAIN.h H_ENCRYPTION.h H_IMAGES.h
	$(CC) $(CFLAGS) -c -o O_ENCRYPTION.o C_ENCRYPTION.c

O_SAVELOAD.o : C_SAVELOAD.c H_MAIN.h H_SAVELOAD.h
	$(CC) $(CFLAGS) -c -o O_SAVELOAD.o C_SAVELOAD.c

O_SEARCHDISPLAY.o : C_SEARCHDISPLAY.c H_MAIN.h H_SEARCHDISPLAY.h
	$(CC) $(CFLAGS) -c -o O_SEARCHDISPLAY.o C_SEARCHDISPLAY.c

clean :
	rm O_MAIN.o O_ADDCRIM.o O_BACKEND.o O_COMPRESSION.o O_EDITCRIM.o O_ENCRYPTION.o O_IMAGES.o O_SAVELOAD.o O_SEARCHDISPLAY.o
